<div class="messageBanner">
    <div class="message">
        Welcome to Blackjack.<small>Click 'Play' to start...</small></div>
    <div class="playButton">
        <a href="<?php echo $this->baseUrl() ?>/index/play">
            <img src="<?php echo $this->baseUrl() ?>/images/play.png" class="playButton" alt="Play">
        </a>
    </div>
    <div class="bannerLinks">
        <a>Show your scores...</a><a>Reset this game!</a></div>
</div>
<div style="position: absolute; left: 0pt; top: 323px; background-color: Black;
    z-index: 10; width: 1920px; height: 100px; display: block;">
</div>
<script>
$(document).ready(function() {
    $('#input1').hide();
    $('#input2').hide();
});
</script>