<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8"></meta>
		<title>Zend Framework BlackJack</title>
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
	    <link href="<?php echo $this->baseUrl() ?>/css/layout.css" rel="stylesheet" type="text/css" />
	    <link href="<?php echo $this->baseUrl() ?>/css/game.css" rel="stylesheet" type="text/css" />
	    <script src="<?php echo $this->baseUrl() ?>/js/blackjack.js" type="text/javascript"></script>
	    <script>var baseUrl = '<?= $this->baseUrl(); ?>';</script>
	</head>
	<body>
	    <div class="page">
	        <div class="header">
				<div id="stats">
				</div>
			</div>
	        <div class="gametable" id="gametable">
	            <div id="dealerContainer" class="boardRow">
	            </div>
	            <div id="playerContainer" class="boardRow">
	            </div>
	            <div title="Deal a new card" class="twistbutton button" id="input1">
	                <input type="submit" value="Hit!" id="hit-button" /></div>
	            <div title="Stay with your current cards" class="stickbutton button" id="input2">
	                <input type="submit" value="Stand!" id="stand-button" /></div>
	        </div>
	        <p class="copy">
	            © 2010 dotDigitalGroup.</p>
	    </div>
		<?php echo $this->layout()->content; ?>
	</body>
</html>
